account_id = "574fdb1eae7e80782a805c4b92f6b626"
compatibility_date = "2022-05-31"
compatibility_flags = ["streams_enable_constructors"]
name = "remix-flags"

main = "entry.worker.ts"

workers_dev = true

[site]
bucket = "../remix-app/public"

[env.dev.vars]
FAUNA_SECRET = "put-your-secret-here"
SESSION_SECRET = "should-be-secure-in-prod"
